### ISSUE TITLE
App crashes after a fresh install

### ISSUE THREAD

**Issue by woniesong92** [KunalKapadia/express-mongoose-es6-rest-api#12]
`gulp serve` fails.

```
$ gulp serve
[19:17:41] Requiring external module babel-register
[19:17:42] Using gulpfile ~/tmp_clones/express-mongoose-es6-rest-api/gulpfile.babel.js
[19:17:42] Starting 'clean'...
[19:17:42] Finished 'clean' after 5.76 ms
[19:17:42] Starting 'serve'...
[19:17:42] Starting 'lint'...
[19:17:42] Starting 'copy'...
[19:17:42] Starting 'babel'...
[19:17:42] Finished 'serve' after 132 ms
[19:17:49] Finished 'copy' after 6.81 s
[19:17:50] Finished 'lint' after 8.47 s
[19:17:50] Finished 'babel' after 8.36 s
[19:17:50] Starting 'nodemon'...
[19:17:50] Finished 'nodemon' after 76 ms
[19:17:50] [nodemon] 1.9.2
[19:17:50] [nodemon] to restart at any time, enter `rs`
[19:17:50] [nodemon] watching: *.*
[19:17:50] [nodemon] starting `node dist/index.js`
/Users/user/tmp_clones/express-mongoose-es6-rest-api/node_modules/mongodb/lib/server.js:242
        process.nextTick(function() { throw err; })
                                      ^

Error: unable to connect to database: mongodb://localhost/express-mongoose-es6-rest-api-development
    at NativeConnection.<anonymous> (/Users/user/tmp_clones/express-mongoose-es6-rest-api/dist/index.js:31:8)
    at emitOne (events.js:90:13)
    at NativeConnection.emit (events.js:182:7)
    at NativeConnection.Connection.error (/Users/user/tmp_clones/express-mongoose-es6-rest-api/node_modules/mongoose/lib/connection.js:449:8)
    at /Users/user/tmp_clones/express-mongoose-es6-rest-api/node_modules/mongoose/lib/connection.js:478:15
    at /Users/user/tmp_clones/express-mongoose-es6-rest-api/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:69:21
    at /Users/user/tmp_clones/express-mongoose-es6-rest-api/node_modules/mongodb/lib/db.js:231:14
    at null.<anonymous> (/Users/user/tmp_clones/express-mongoose-es6-rest-api/node_modules/mongodb/lib/server.js:240:9)
    at g (events.js:273:16)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at null.<anonymous> (/Users/user/tmp_clones/express-mongoose-es6-rest-api/node_modules/mongodb-core/lib/topologies/server.js:218:12)
    at g (events.js:273:16)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at null.<anonymous> (/Users/user/tmp_clones/express-mongoose-es6-rest-api/node_modules/mongodb-core/lib/connection/pool.js:119:12)
    at g (events.js:273:16)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at Socket.<anonymous> (/Users/user/tmp_clones/express-mongoose-es6-rest-api/node_modules/mongodb-core/lib/connection/connection.js:151:49)
    at Socket.g (events.js:273:16)
    at emitOne (events.js:90:13)
[19:17:51] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by KunalKapadia** [comment]
Hi Howon,

MongoDB isn't running on your system. Can you please make sure you have
mongoDB up and running at port 27017.

Regards,
Kunal

**Comment by woniesong92** [comment]
That was it
