### ISSUE TITLE
'gulp serve' not running in Node.js 6.2.2(NPM 3.9.5)

### ISSUE THREAD

**Issue by colinwitkamp** [KunalKapadia/express-mongoose-es6-rest-api#31]
After running  'npm install', I tried to run 'gulp serve'.
I am getting the following error:

[12:57:48] Failed to load external module babel-register
[12:57:48] Failed to load external module babel-core/register
[12:57:48] Failed to load external module babel/register
/Volumes/MACDATA/Current_Work/uslikey/project/express-mongoose-es6-rest-api/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)

So I installed 'babel-register', 'babel-core/register' and 'babel/register' by 'npm install' .
After that, when I run 'gulp serve'  I faced the following:

[13:15:23] Requiring external module babel-register
module.js:442
    throw err;
    ^

Error: Cannot find module './_baseClone'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/MACDATA/Current_Work/uslikey/project/express-mongoose-es6-rest-api/node_modules/babel-plugin-add-module-exports/node_modules/babel-template/node_modules/lodash/cloneDeep.js:1:79)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/MACDATA/Current_Work/uslikey/project/express-mongoose-es6-rest-api/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

Everything was all right in Node.js 4.4.3

**Comment by KunalKapadia** [comment]
@colinwitkamp Are you still getting the error ?

Test suite successfully runs against node.js v4.5 and v6.6.

**Comment by colinwitkamp** [comment]
Hey,
It is working correctly now!
Thanks for your support!
