### ISSUE TITLE
Build/Test failing

### ISSUE THREAD

**Issue by osahner** [KunalKapadia/express-mongoose-es6-rest-api#310]
```shell
$ git clone https://github.com/KunalKapadia/express-mongoose-es6-rest-api.git
Cloning into 'express-mongoose-es6-rest-api'...
remote: Counting objects: 1108, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 1108 (delta 3), reused 0 (delta 0), pack-reused 1098
Receiving objects: 100% (1108/1108), 239.54 KiB | 0 bytes/s, done.
Resolving deltas: 100% (610/610), done.
$ cd express-mongoose-es6-rest-api/
$ yarn
yarn install v0.20.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "express-validation@1.0.1" has incorrect peer dependency "joi@^9.0.4".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 13.25s.
$ yarn test
yarn test v0.20.3
$ cross-env NODE_ENV=test ./node_modules/.bin/mocha --ui bdd --reporter spec --colors --compilers js:babel-core/register server/tests --recursive express-mongoose-es6-rest-api/config/config.js:35
  throw new Error('Config validation error: ' + error.message);
  ^

Error: Config validation error: child "JWT_SECRET" fails because ["JWT_SECRET" is required]
    at Object.<anonymous> (express-mongoose-es6-rest-api/config/config.js:30:9)
    at Module._compile (module.js:570:32)
    at loader (express-mongoose-es6-rest-api/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (express-mongoose-es6-rest-api/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (express-mongoose-es6-rest-api/index.js:5:1)
    at Module._compile (module.js:570:32)
    at loader (express-mongoose-es6-rest-api/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (express-mongoose-es6-rest-api/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (express-mongoose-es6-rest-api/server/tests/auth.test.js:5:1)
    at Module._compile (module.js:570:32)
    at loader (express-mongoose-es6-rest-api/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (express-mongoose-es6-rest-api/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at express-mongoose-es6-rest-api/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (express-mongoose-es6-rest-api/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (express-mongoose-es6-rest-api/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (express-mongoose-es6-rest-api/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
error Command failed with exit code 1.
```

**Comment by KunalKapadia** [comment]
@osahner You'll need to create a `.env` file which can be same as `.env.example`. 
If you are runnings tests on CI/CD server then you'll need to set env vars on it since `.env` file should not be committed.

Will soon be adding this stuff to README as we have moved to `dotenv` for managing different envs.

**Comment by osahner** [comment]
@KunalKapadia I see. 👍
