### ISSUE TITLE
Coverage failed

### ISSUE THREAD

**Issue by sergio11** [KunalKapadia/express-mongoose-es6-rest-api#35]
Hi, I am having problems with the plugin gulp -istanbul.  

When I do commit, all tests are passed but the process fails to make the coverage

```
  38 passing (4s)

=============================== Coverage summary ===============================
Statements   : 89.46% ( 1163/1300 ), 75 ignored
Branches     : 84.71% ( 277/327 ), 85 ignored
Functions    : 73.48% ( 241/328 ), 1 ignored
Lines        : 85.86% ( 777/905 )
================================================================================
[13:58:10] 'test' errored after 9.18 s
[13:58:10] Error in plugin 'gulp-istanbul'
Message:
    Coverage failed
[13:58:10] Error in plugin 'run-sequence(test)'
Message:
    Coverage failed
Stack:
    at finish (/home/sergio/proyects/instangular-rest-api/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/home/sergio/proyects/instangular-rest-api/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/home/sergio/proyects/instangular-rest-api/node_modules/orchestrator/index.js:264:8)
    at /home/sergio/proyects/instangular-rest-api/node_modules/orchestrator/index.js:275:23
    at finish (/home/sergio/proyects/instangular-rest-api/node_modules/orchestrator/lib/runTask.js:21:8)
    at DestroyableTransform.<anonymous> (/home/sergio/proyects/instangular-rest-api/node_modules/orchestrator/lib/runTask.js:52:4)
    at DestroyableTransform.f (/home/sergio/proyects/instangular-rest-api/node_modules/once/once.js:17:25)
    at emitOne (events.js:82:20)
    at DestroyableTransform.emit (events.js:169:7)
    at DestroyableTransform.<anonymous> (/home/sergio/proyects/instangular-rest-api/node_modules/gulp-istanbul/index.js:178:12)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
    at endReadableNT (/home/sergio/proyects/instangular-rest-api/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:865:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
[13:58:10] completed !!
npm ERR! Test failed.  See above for more details.

```

**Comment by KunalKapadia** [comment]
Hi @sergio11 

Its because we have enforced code coverage of 80% globally.
You can update it as per your requirements on https://github.com/KunalKapadia/express-mongoose-es6-rest-api/blob/master/gulpfile.babel.js#L21

**Comment by sergio11** [comment]
ok, thanks
