### ISSUE TITLE
Add SWAGGER 

### ISSUE THREAD

**Issue by duard** [KunalKapadia/express-mongoose-es6-rest-api#427]
I'm trying to implement swagger api documentation in this project based on this page https://html5hive.org/how-to-create-rest-api-with-node-js-and-express/ but I get 

```
Error: Cannot find module './swagger.json'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/duard/Development/api-rest/dist/index.js:45:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

**Comment by Ebsy** [comment]
Have a look through this
https://github.com/KunalKapadia/express-mongoose-es6-rest-api/pull/346/files

**Comment by duard** [comment]
I follow this article and everything works https://medium.com/@tkssharma/swagger-with-existing-node-app-for-api-definition-9e0bd9fdd2af Thanks !
