### ISSUE TITLE
api not found

### ISSUE THREAD

**Issue by MusarrathS** [KunalKapadia/express-mongoose-es6-rest-api#428]
{"message":"Not Found","stack":"Error: API not found\n    at APIError.ExtendableError (/home/syed/Documents/api/UserRole/dist/server/helpers/APIError.js:35:11)\n    at new APIError (/home/syed/Documents/api/UserRole/dist/server/helpers/APIError.js:63:101)\n    at /home/syed/Documents/api/UserRole/dist/config/express.js:122:13\n    at Layer.handle [as handle_request] (/home/syed/Documents/api/UserRole/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/syed/Documents/api/UserRole/node_modules/express/lib/router/index.js:312:13)\n    at /home/syed/Documents/api/UserRole/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/home/syed/Documents/api/UserRole/node_modules/express/lib/router/index.js:330:12)\n    at next (/home/syed/Documents/api/UserRole/node_modules/express/lib/router/index.js:271:10)\n    at Layer.handle [as handle_request] (/home/syed/Documents/api/UserRole/node_modules/express/lib/router/layer.js:91:12)\n    at trim_prefix (/home/syed/Documents/api/UserRole/node_modules/express/lib/router/index.js:312:13)\n    at /home/syed/Documents/api/UserRole/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/home/syed/Documents/api/UserRole/node_modules/express/lib/router/index.js:330:12)\n    at next (/home/syed/Documents/api/UserRole/node_modules/express/lib/router/index.js:271:10)\n    at /home/syed/Documents/api/UserRole/node_modules/express-winston/index.js:306:9\n    at Layer.handle [as handle_request] (/home/syed/Documents/api/UserRole/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/syed/Documents/api/UserRole/node_modules/express/lib/router/index.js:312:13)\n    at /home/syed/Documents/api/UserRole/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/home/syed/Documents/api/UserRole/node_modules/express/lib/router/index.js:330:12)\n    at next (/home/syed/Documents/api/UserRole/node_modules/express/lib/router/index.js:271:10)\n    at cors (/home/syed/Documents/api/UserRole/node_modules/cors/lib/index.js:179:7)\n    at /home/syed/Documents/api/UserRole/node_modules/cors/lib/index.js:229:17\n    at originCallback (/home/syed/Documents/api/UserRole/node_modules/cors/lib/index.js:218:15)"}

**Comment by dylanbromby** [comment]
What URL/endpoint are you trying to hit?

**Comment by MusarrathS** [comment]
its working now i have to put api in front now its done

**Comment by kartikwar** [comment]
Same issue is coming for me. I am hitting localhost:port/user/

**Comment by kartikwar** [comment]
Same issue for me . I am hitting the endpoint /api/{routename}/path. It says api not found

**Comment by aravindhkm** [comment]
@kartikwar how do fix this issue?
