### ISSUE TITLE
TypeError: Cannot read property 'getAllInfo' of undefined during 500 error

### ISSUE THREAD

**Issue by gen4sp** [kunalkapadia/express-mongoose-es6-rest-api#434]
```
TypeError: Cannot read property 'getAllInfo' of undefined
    at /Users/gen4/Gits/tw/server/node_modules/express-winston/index.js:134:47
    at Layer.handle_error (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:310:13)
    at /Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:310:13)
    at /Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:271:10)
    at /Users/gen4/Gits/tw/server/dist/config/express.js:124:12
    at Layer.handle_error (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:310:13)
    at /Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:330:12)
    at Immediate.next (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:271:10)
    at Immediate.<anonymous> (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:618:15)
    at runCallback (timers.js:787:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
RangeError: Invalid status code: undefined
    at ServerResponse.writeHead (_http_server.js:188:11)
    at ServerResponse.writeHead (/Users/gen4/Gits/tw/server/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/Users/gen4/Gits/tw/server/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:179:8)
    at ServerResponse.end (/Users/gen4/Gits/tw/server/node_modules/compression/index.js:102:14)
    at ServerResponse.res.end (/Users/gen4/Gits/tw/server/node_modules/express-winston/index.js:207:17)
    at ServerResponse.send (/Users/gen4/Gits/tw/server/node_modules/express/lib/response.js:205:10)
    at ServerResponse.json (/Users/gen4/Gits/tw/server/node_modules/express/lib/response.js:250:15)
    at /Users/gen4/Gits/tw/server/dist/config/express.js:146:26
    at Layer.handle_error (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:310:13)
    at /Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/layer.js:73:5)
    at trim_prefix (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:310:13)
    at /Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:310:13)
    at /Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:271:10)
    at /Users/gen4/Gits/tw/server/dist/config/express.js:124:12
    at Layer.handle_error (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:310:13)
    at /Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:330:12)
    at Immediate.next (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:271:10)
    at Immediate._onImmediate (/Users/gen4/Gits/tw/server/node_modules/express/lib/router/index.js:618:15)
    at runCallback (timers.js:787:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```

**Comment by voodee** [comment]
any progress?
