### ISSUE TITLE
getting this error when I run - yarn test:coverage

### ISSUE THREAD

**Issue by idanb11** [KunalKapadia/express-mongoose-es6-rest-api#458]
```
$ cross-env NODE_ENV=test ./node_modules/.bin/istanbul cover _mocha -- --ui bdd --reporter spec --colors server --recursive

=============================== Coverage summary ===============================
Statements   : 0% ( 0/240 )
Branches     : 0% ( 0/29 )
Functions    : 0% ( 0/61 )
Lines        : 0% ( 0/239 )
================================================================================
C:\Users\Idanb11\Work\Il Makiage\microservice-boilerplate\node_modules\.bin\_mocha.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module.replacementCompile (C:\Users\Idanb11\Work\Il Makiage\microservice-boilerplate\node_modules\append-transform\index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.<anonymous> (C:\Users\Idanb11\Work\Il Makiage\microservice-boilerplate\node_modules\append-transform\index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by idanb11** [comment]
I get the same error when I run 

`yarn test:check-coverage`
